In [1]:
import numpy as np

import matplotlib
matplotlib.use('TkAgg')
import matplotlib.pyplot as plt

In [2]:
def sigmoid(x):
    return (1/(1+ np.exp(-x)))

In [3]:
def calc_z(theta, j):
    return theta.dot(j)

In [4]:
def calc_alpha(z):
    alpha = []
    for m in z:
        alpha.append(sigmoid(m))
    return alpha

In [5]:
def calc_total_error(a):
    total_error = (pow((y[0]-a[0]), 2))*0.5 + (pow((y[1]-a[1]), 2))*0.5 
    return total_error

In [6]:
# a is aplha out and a_h is alpha hidden
def calc_theta_new(theta_2, a, a_h):
    
    # calculating theta 2
    term_0 = (a[0]-y[0])*a[0]*(1-a[0])
    term_1 = (a[1]-y[1])*a[1]*(1-a[1])
    
    theta10 = term_0*a_h[0]
    theta11 = term_0*a_h[1]
    theta12 = term_0*a_h[2]
    theta20 = term_1*a_h[0]
    theta21 = term_1*a_h[1]
    theta22 = term_1*a_h[2]
    a = np.asarray(a)
    theta_2_new_dash = np.asarray([[theta10, theta11, theta12], [theta20, theta21, theta22]])
    theta_2_new = theta_2  - (a.dot(theta_2_new_dash))
    
    # calculating theta 1
    
    term_2 = (a_h[1]*(1-a_h[1]))
    term_3 = (a_h[2]*(1-a_h[2]))
    
    theta10_1 = (term_0*theta_2[0,1] + term_1*theta_2[1,1])*(term_2*x[0])
    theta11_1 = (term_0*theta_2[0,1] + term_1*theta_2[1,1])*(term_2*x[1])
    theta12_1 = (term_0*theta_2[0,1] + term_1*theta_2[1,1])*(term_2*x[2])
    theta20_1 = (term_0*theta_2[0,2] + term_1*theta_2[1,2])*(term_3*x[0])
    theta21_1 = (term_0*theta_2[0,2] + term_1*theta_2[1,2])*(term_3*x[1])
    theta22_1 = (term_0*theta_2[0,2] + term_1*theta_2[1,2])*(term_3*x[2])
    
    theta_1_new = np.asarray([[theta10_1, theta11_1, theta12_1], [theta20_1, theta21_1, theta22_1]])
    
    return theta_1_new, theta_2_new

In [7]:
# defining initial and given values.
x = np.array([1, 0.05, 1])                  # first element is the bias.
y = np.array([0.01, 0.99])
iter = 300
theta_1 = np.array([[np.random.uniform(0,1) for m in range(3)] for n in range(2)])
theta_2 = np.array([[np.random.uniform(0,1) for m in range(3)] for n in range(2)])
print 'theta_1 is : \n', theta_1, '\n'
print 'theta_2 is : \n', theta_2

theta_1_array = []
theta_2_array = []

theta_1 is : 
[[ 0.07406306  0.36349664  0.70947251]
 [ 0.53902754  0.85020895  0.92547937]] 

theta_2 is : 
[[ 0.51810977  0.0657535   0.8882969 ]
 [ 0.67962227  0.52799877  0.01727844]]


In [8]:
fig = plt.figure()
ax = fig.add_subplot(1, 1, 1)
ax.set_title('Neural Networks')
ax.set_xlabel('iteration')
ax.set_ylabel('cost')

for i in range(iter):
    # forward propogation and backward propogation.
    z1 = calc_z(theta_1, x)
    
    alpha_hidden_dash = calc_alpha(z1)
    
    alpha_hidden = [1] + alpha_hidden_dash

    z2 = calc_z(theta_2, alpha_hidden)

    alpha_out = calc_alpha(z2)
    
    total_error = calc_total_error(alpha_out)
    
    print "Total error for iteration ", i," is : ", total_error, "\n"

    theta_1, theta_2 = calc_theta_new(theta_2, alpha_out, alpha_hidden)
    theta_1_array.append(theta_1)
    theta_2_array.append(theta_2)
       
    ax.plot(i, total_error, linestyle='None', marker='o', markersize=5, color='blue', label='')

Total error for iteration  0  is :  0.330403885045 

Total error for iteration  1  is :  0.286270619934 

Total error for iteration  2  is :  0.280036345805 

Total error for iteration  3  is :  0.273947285008 

Total error for iteration  4  is :  0.268841874593 

Total error for iteration  5  is :  0.26462247704 

Total error for iteration  6  is :  0.261174482249 

Total error for iteration  7  is :  0.258380217736 

Total error for iteration  8  is :  0.256129086458 

Total error for iteration  9  is :  0.254322824091 

Total error for iteration  10  is :  0.252877335076 

Total error for iteration  11  is :  0.251722456646 

Total error for iteration  12  is :  0.250800653323 

Total error for iteration  13  is :  0.250065289158 

Total error for iteration  14  is :  0.249478849834 

Total error for iteration  15  is :  0.249011302618 

Total error for iteration  16  is :  0.248638670974 

Total error for iteration  17  is :  0.248341839385 

Total error for iteration  18  is :  0.

Total error for iteration  171  is :  0.247304195556 

Total error for iteration  172  is :  0.247304195584 

Total error for iteration  173  is :  0.247304195609 

Total error for iteration  174  is :  0.247304195632 

Total error for iteration  175  is :  0.247304195652 

Total error for iteration  176  is :  0.247304195671 

Total error for iteration  177  is :  0.247304195689 

Total error for iteration  178  is :  0.247304195704 

Total error for iteration  179  is :  0.247304195719 

Total error for iteration  180  is :  0.247304195732 

Total error for iteration  181  is :  0.247304195744 

Total error for iteration  182  is :  0.247304195754 

Total error for iteration  183  is :  0.247304195764 

Total error for iteration  184  is :  0.247304195773 

Total error for iteration  185  is :  0.247304195782 

Total error for iteration  186  is :  0.247304195789 

Total error for iteration  187  is :  0.247304195796 

Total error for iteration  188  is :  0.247304195802 

Total erro

In [9]:
print "z1 is : ", z1
print "z2 is : ", z2

print "\nalpha_hidden : ", alpha_hidden

print "alpha_out is : " , alpha_out
print "\ntheta_1_new is : \n", theta_1, "\n"
print "theta_2_new is : \n", theta_2, "\n"

print "Total error for is : ", total_error, "\n"

z1 is :  [-0.02867245  0.05396963]
z2 is :  [-0.00114758 -0.05908416]

alpha_hidden :  [1, 0.49283237810901187, 0.51348913420172926]
alpha_out is :  [0.49971310583924594, 0.48523325614615009]

theta_1_new is : 
[[-0.01431833 -0.00071592 -0.01431833]
 [ 0.02695113  0.00134756  0.02695113]] 

theta_2_new is : 
[[-0.13901309 -0.27250022  0.53002572]
 [ 0.02249941  0.18974505 -0.34099274]] 

Total error for is :  0.247304195866 



In [10]:
ax.legend()
fig.show()

C:\Users\Aditya\Anaconda2\lib\site-packages\matplotlib\axes\_axes.py:545: UserWarning: No labelled objects found. Use label='...' kwarg on individual plots.
  warnings.warn("No labelled objects found. "


In [11]:
fig_theta1 = plt.figure()
ax10 = fig_theta1.add_subplot(2, 3, 1)
ax11 = fig_theta1.add_subplot(2, 3, 2)
ax12 = fig_theta1.add_subplot(2, 3, 3)
ax20 = fig_theta1.add_subplot(2, 3, 4)
ax21 = fig_theta1.add_subplot(2, 3, 5)
ax22 = fig_theta1.add_subplot(2, 3, 6)

for i,a in enumerate(theta_1_array):
    ax10.plot(i, a[0,0], linestyle='None', marker='.', markersize=2, color='blue', label='')
    ax11.plot(i, a[0,1], linestyle='None', marker='.', markersize=2, color='green', label='')
    ax12.plot(i, a[0,2], linestyle='None', marker='.', markersize=2, color='red', label='')
    ax20.plot(i, a[1,0], linestyle='None', marker='.', markersize=2, color='yellow', label='')
    ax21.plot(i, a[1,1], linestyle='None', marker='.', markersize=2, color='purple', label='')
    ax22.plot(i, a[1,2], linestyle='None', marker='.', markersize=2, color='black', label='')
fig_theta1.show()

In [12]:
fig_theta2 = plt.figure()
ax_2_10 = fig_theta2.add_subplot(2, 3, 1)
ax_2_11 = fig_theta2.add_subplot(2, 3, 2)
ax_2_12 = fig_theta2.add_subplot(2, 3, 3)
ax_2_20 = fig_theta2.add_subplot(2, 3, 4)
ax_2_21 = fig_theta2.add_subplot(2, 3, 5)
ax_2_22 = fig_theta2.add_subplot(2, 3, 6)

for i,a in enumerate(theta_2_array):
    ax_2_10.plot(i, a[0,0], linestyle='None', marker='.', markersize=2, color='blue', label='')
    ax_2_11.plot(i, a[0,1], linestyle='None', marker='.', markersize=2, color='green', label='')
    ax_2_12.plot(i, a[0,2], linestyle='None', marker='.', markersize=2, color='red', label='')
    ax_2_20.plot(i, a[1,0], linestyle='None', marker='.', markersize=2, color='yellow', label='')
    ax_2_21.plot(i, a[1,1], linestyle='None', marker='.', markersize=2, color='purple', label='')
    ax_2_22.plot(i, a[1,2], linestyle='None', marker='.', markersize=2, color='black', label='')
fig_theta2.show()